Slideshow images
Montana-Code-School/DreamsBack pull request #20
Opened 2019-04-09 22:38 UTC by megalobamboozlementarianism

2019-04-09 22:40 UTC, ed42311 commented on models.js
> +  savedPlace: {
Is this confusing in terms of how the user is interacting with the page?

2019-04-09 22:43 UTC, ceotter commented on models.js
> +  savedPlace: {
Make this name more descriptive.

2019-04-09 22:53 UTC, ceotter commented on server.js
> +app.use((req, res, next)=>{
Shouldn't be run in production. Delete if you want.

2019-04-09 22:56 UTC, ceotter requested changes
See above comments.

2019-04-10 16:06 UTC, ceotter approved these changes

2019-04-10 16:06 UTC, merged